### ISSUE TITLE
투표 삭제 / 투표 즉시 종료 API 연결

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#147]
## 📌 Issue

투표 삭제 / 투표 즉시 종료 API 연결

## 📝 To-do

- [x] action sheet UI
- [x] 투표 삭제 API
- [x] 투표 즉시 종료 API
