### ISSUE TITLE
로그인할때 회원정보 있는지 체크

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#15]
## 📌 Issue
- 로그인할때  status 체크를 통해 해당하는 뷰로 넘어가게 하기
## 📝 To-do
- [x] 온보딩페이지에서 로그인 했을 때 회원정보가 다 들어가있으면 메인뷰로 넘어가기
- [x] 없으면 동의하기 bottomSheetView열리게 하기 
- [x] bottomSheetView모두 동의하기하면 프로필뷰로 넘어가게 하기
