### ISSUE TITLE
Push Notification 연결작업 

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#157]
## 📌 Issue
드디어 합니다. 푸쉬 노티 연결작업을 하고 해당하는 뷰로 이동하도록 Path관리 & silent Push업데이트
## 📝 To-do
- [ ] silentPush를 이용하여 다른 디바이스에서 소비성향업데이트했을때 해당하는 기기도 같이 업데이트 되도록 구현
- [ ] 대댓글 달렷을때 알림을받고 넘어가기
- [ ] 내 게시글에 댓글이 달렸을때 알림받고 넘어가기
- [ ] 투표가 종료된 경우 알림받기
