### ISSUE TITLE
프로필 세팅 뷰 버그 Fix

### ISSUE THREAD

**Issue by snacknam** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#181]
## 📌 Issue

프로필 세팅 뷰 버그 Fix

## 📝 To-do

- [x] 뒤로가기 버튼 사라짐 이슈
- [x] 뷰에 재진입 시 초기화 이슈
- [x] 이미지만 바뀌어도 완료 선택 가능하도록 수정
- [x] 이미지 재설정 이슈
- [x] 이미지 삭제 시 기본 이미지로 설정
- [x] 닉네임 수정없이 중복확인 시 처리
- [x] 소비성향 없을 시 뷰 처리
