### ISSUE TITLE
버그 fix

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#182]
## 📌 Issue

버그 fix

## 📝 To-do

- [ ] 로그아웃 디바이스 토큰 추가
- [ ] 온보딩뷰 이용약관/개인정보 정책 추가하기
- [ ] 차단했을 때 refresh 하기
- [ ] 링크뷰 x 버튼 안 보이는 거 수정
