### ISSUE TITLE
프로필설정뷰 레이아웃 그리기 및 기능 추가

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#2]
## 📌 Issue

프로필설정뷰 레이아웃 그리기

## 📝 To-do

- [x] 프로필 설정뷰 레이아웃 그리기
- [x] 앨범 접근 권한 추가
- [x] 앨범 접근
- [x] 앨범에서 사진 가져와서 프로필 등록
- [x] 학년 드롭다운 선택
- [ ] 조건 추가
