### ISSUE TITLE
앱 내 모든 API 통신을 위한 통합 API Manager

### ISSUE THREAD

**Issue by snacknam** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#35]
## 📌 Issue
앱 내 모든 API 통신을 하나의 API Manager로 통합하여 케이스별로 관리

## 📝 To-do
- [x] API 통신 별 케이스 정리
- [x] APIManager로 통합
- [x] 각 뷰모델 별 APIManager 적용
- [x] refreshToken 메소드 통합
