### ISSUE TITLE
APIManager 헤더 수정 및 파라미터 추가

### ISSUE THREAD

**Issue by snacknam** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#48]
## 📌 Issue
APIManager 헤더 수정하고 파라미터  이름 추가

## 📝 To-do
- [x] APIManger 파라미터 이름 추가
- [x] request 헤더 수정
- [x] encoding type 추가
