### ISSUE TITLE
학교 검색 레이아웃 수정사항 반영

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#59]
## 📌 Issue

학교 검색 레이아웃 수정사항 반영

## 📝 To-do

- [ ] 검색 결과 없을 때 UI
- [ ] textField 엔터 누르면 색 변경
- [ ] textField를 누르면 textField 비워짐
