### ISSUE TITLE
댓글 수정 & 버그 잡기

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#66]
## 📌 Issue
- 댓글 UI 수정
- 대댓글 바로 업데이트 안되는거 수정

## 📝 To-do

- [ ] 답글에 답글 안되게 막기
- [ ] 댓글 누르면 위에 게시물이 사라지는 것이 아니라 스크롤해서 볼 수 있도록 하기
- [ ] 누구에게 답글달고 있는지 볼수 있게하기
