### ISSUE TITLE
메인뷰 UI 수정 및 상세조회 api 통신

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#67]
## 📌 Issue

좋아요 등록/취소 및 UI 수정

## 📝 To-do

- [x] 메인뷰 UI - 태그 삭제
- [x] 메인뷰 UI - 조회수 오류 수정
- [ ] 메인뷰 - 투표 오류 수정
- [x] 메인뷰 - postCategoryType에 따라 투표 문구 변경 
- [x] 상세 조회 api 통신
