### ISSUE TITLE
학교 검색 등록 / 통합 검색 레이아웃 

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#86]
## 📝 To-do

- [x] 학교 검색 등록 레이아웃 수정
- [x] 통합 검색 레이아웃 제작
- [x] Secret key 재등록
