### ISSUE TITLE
온보딩 디자인 적용

### ISSUE THREAD

**Issue by snacknam** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#87]
## 📌 Issue
스플래시 뷰, 로그인 뷰, 서비스 이용약관 동의 뷰 디자인 적용

## 📝 To-do

- [x] 스플래시 화면 적용
- [x] 로그인 뷰 디자인 적용
- [x] 서비스 이용약관 뷰 디자인 적용
