### ISSUE TITLE
학교 검색 및 등록 기능 개발

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#9]
## 📌 Issue

학교 검색 및 등록 기능 개발

## 📝 To-do

- [x] 커리어넷 학교 정보 api 통신
- [x] 목업 디자인 추가
- [x] 모델 추가
- [x] 지역/학교 이름 가져오기
